# Generated by Django 5.2.10 on 2026-02-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pendingsignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingsignup',
            old_name='usernmae',
            new_name='username',
        ),
    ]
