# Generated by Django 5.2.10 on 2026-02-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_usernmae_pendingsignup_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingSignup',
        ),
    ]
